# Generated by Django 2.2.1 on 2019-11-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='regmodel',
            name='confirm_password',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='regmodel',
            name='enter_answer',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='regmodel',
            name='gender',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='regmodel',
            name='security_question',
            field=models.CharField(blank=True, choices=[('WBD', 'What is your birthdate?'), ('OPN', 'What is your Old Phone Number?'), ('YPN', 'What is your Petname?')], max_length=3, null=True),
        ),
    ]
