# Generated by Django 2.2.1 on 2019-11-27 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth_app', '0002_auto_20191122_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regmodel',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'FeMale')], max_length=2, null=True),
        ),
    ]
